services:
  postgresql:
    container_name: devps-app-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: MyPass01
      POSTGRES_USER: todo
      POSTGRES_DB: todo
    volumes:
      - devps-app-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - deovps-app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fulano@email.com"
      PGADMIN_DEFAULT_PASSWORD: "MyPass01"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - deovps-app

  deovps-app_front:
    image: jersonb/devops-app:latest
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  deovps-app_back:
    image: jersonb/devops-back:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings:Postgres: ${POSTGRES} 
    ports:
      - 8080:8080
    networks:
      - deovps-app
    depends_on:
      - postgresql

networks:
  deovps-app:
  
volumes:
  devps-app-postgres: